### ISSUE TITLE
报错login_error#INFO Error，err_code=1

### ISSUE THREAD

**Issue by ydbcxc** [ice-tong/SrunClient#1]
我们学校的限制是只能使用网页认证，认证客户端的系统必须为Win10 有解决办法嘛 大佬

**Comment by ice-tong** [comment]
> 我们学校的限制是只能使用网页认证，认证客户端的系统必须为Win10 有解决办法嘛 大佬

你们学校是否使用的是深澜网关，是否将代码中的认证地址改成你们学校的认证地址。
网页端和win10并不是限制，本质上都是用的http协议请求，可以尝试更换user-agent请求头来模拟成浏览器的请求行为。

**Comment by ydbcxc** [comment]
哎呀 才发现这个也是我提交的 。。。
