### ISSUE TITLE
关于User-Agent

### ISSUE THREAD

**Issue by ydbcxc** [ice-tong/SrunClient#2]
我们学校限制登陆认证的设备只能是Win10 系统 ，请问如何添加User-Agent？
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

**Comment by ice-tong** [comment]
https://github.com/ice-tong/SrunClient/blob/f2515f762b467173d780a3ffcb8400999e18b1c7/srun.py#L69

**Comment by ydbcxc** [comment]
能用了能用了 谢谢谢谢 我是小白 之前没看懂
